version: "0.0"
services:
  db:
    build: ./psql_db_init
    ports:
      - "${HOST_PORT}:5432"
    env_file:
      - .env
    volumes:
      - ./psql_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
